AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws:states:opt-in
Resources:
  EC2lambdastart:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: s3://sam-deploy-lambda-serverless/89c897c4406f32ad4ae971f008c73594
      Description: aws:states:opt-in
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::618624782178:role/EC2_handleInstances
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 7 ? * MON-FRI *)
