AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  StopEC2TAGGED:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 179
      Role: 'arn:aws:iam::748659484642:role/EC2_StopInstances'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(7 minutes)
